service: organizations-api

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'

functions:
  createOrganization:
    handler: src/routes.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
  tscpaths:
    buildPath: .build
    tsconfigPath: tsconfig.json
