import { User } from '@common/entities/user.entity';
import { ICustomBaseEntity } from '@common/entities/interfaces/custom-base-entity';

export type IUserLoginParams = {
  email: string;
  password: string;
};

type AutoGeneratedUserFields = keyof ICustomBaseEntity;

export interface IUserDataSource {
  findById(userId: string): Promise<User | null>;
  findByEmail(email: string): Promise<User | null>;
  findByEmailAndPassword(payload: IUserLoginParams): Promise<User | null>;
  createOne(payload: Omit<User, AutoGeneratedUserFields>): Promise<User>;
  updateOne(userId: string, payload: Partial<User>): Promise<Partial<User>>;
}

export const USER_DATASOURCE_PROVIDER = 'UserDataSource';
