import { IUser } from '@common/entities/interfaces/user';
import { ICustomBaseEntity } from '@common/entities/interfaces/custom-base-entity';

type AutoGeneratedUserFields = keyof ICustomBaseEntity | 'userId';

export class CreateUserInput implements Omit<IUser, AutoGeneratedUserFields> {
  organizationId: string;

  firstName: string;

  lastName: string;

  email: string;

  phoneNumber: string;

  password: string;
}
