import { IUser } from '@common/entities/interfaces/user';
import { IBaseEntity } from '@common/entities/interfaces/base-entity';

type AutoGeneratedUserFields = keyof IBaseEntity;

export class CreateUserInput implements Omit<IUser, AutoGeneratedUserFields> {
  organizationId: string;

  firstName: string;

  lastName: string;

  email: string;

  phoneNumber: string;

  password: string;
}
