import { ICustomBaseEntity } from '@common/entities/interfaces/custom-base-entity';
import { IOrganization } from '@common/entities/interfaces/organization';
import { IOrganizationLocation } from '@common/entities/interfaces/organization-location';
import { CreateUserInput } from '@modules/users/models/create-user-input';

type AutoGeneratedOrganizationFields = keyof ICustomBaseEntity | 'organizationId';

export class CreateOrganizationInput
  implements Omit<IOrganization, AutoGeneratedOrganizationFields>
{
  name: string;

  organizationRepresentantId: string;

  businessSegment: string;

  user: CreateUserInput;

  locations: IOrganizationLocation[];
}
