import { IBaseEntity } from '@common/entities/interfaces/base-entity';
import { Organization } from '@common/entities/implementations/organization.entity';

type AutoGeneratedOrganizationFields = keyof IBaseEntity;

export interface IOrganizationDataSource {
  findById(organizationId: string): Promise<Organization | null>;
  create(
    payload: Omit<Organization, AutoGeneratedOrganizationFields>
  ): Promise<Organization>;
  updateOne(
    organizationId: string,
    payload: Partial<Organization>
  ): Promise<Partial<Organization>>;
}

export const ORGANIZATION_DATASOURCE_PROVIDER = 'OrganizationDataSource';
